player:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\PlayerController

challenge:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\ChallengeController

challenge:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\WeeklychallengeController

notification:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\NotificationController

userStatistics:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\UserStatisticsController