player:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\PlayerController

challenge:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\ChallengeController

notification:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\NotificationController

userStatistics:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\UserStatisticsController

weeklyChallenge:
    type:     rest
    resource: Mimazoo\SoaBundle\Controller\WeeklychallengeController