imports:
    - { resource: config_dev.yml }
    
parameters:
    database_name:     pigdb_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
