parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     pigdb_dev
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    oauth_token:       8HNRYK3lY5Sil_O3bpOZlnMyX5mj0rk3v5N0mxmVbPs
